import { ParkingLotRate } from "../../../parkingLotRates";
import {
  rateTypePresent,
  validateLotID,
  validateTimeRange,
} from "./validators";

export class ParkingLotRatesClientModel extends ParkingLotRate {
  static kRateId = "rateId";
  static kLotId = "lotId";
  static kRateType = "rateType";
  static kRate = "rate";
  static kNightRate = "nightRate";
  static kMinimum = "minimum";
  static kMaximum = "maximum";
  static kDiscount = "discount";
  static kDynamicPricing = "dynamicPricing";
  static kCreatedAt = "createdAt";

  static fromEntity(
    parkingLotRate: ParkingLotRate
  ): ParkingLotRatesClientModel {
    return Object.assign(ParkingLotRatesClientModel.empty(), parkingLotRate);
  }

  static empty(): ParkingLotRatesClientModel {
    return new ParkingLotRatesClientModel(
      "", // rateId
      "", // lotId
      null, // rateType
      0, // rate
      undefined, // nightRate
      0, // minimum
      0, // maximum
      undefined, // discount
      undefined, // dynamicPricing
      new Date() // createdAt
    );
  }

  private static _validate(body: any) {
    validateLotID(body);
    rateTypePresent(body);
    validateTimeRange(body);
  }

  static validate(body: any): ParkingLotRatesClientModel {
    this._validate(body);

    return new ParkingLotRatesClientModel(
      null, // rateId is null as it will be generated by Firestore
      body[this.kLotId],
      body[this.kRateType],
      body[this.kRate],
      body[this.kNightRate],
      body[this.kMinimum],
      body[this.kMaximum],
      body[this.kDiscount],
      body[this.kDynamicPricing],
      null // createdAt is null as it will be generated by Firestore
    );
  }

  toBodyPublicRate(): any {
    // Convert the instance of ParkingLotRatesClientModel to a form suitable for public viewing
    return {
      [ParkingLotRatesClientModel.kRateId]: this.rateId,
      [ParkingLotRatesClientModel.kLotId]: this.lotId,
      [ParkingLotRatesClientModel.kRateType]: this.rateType,
      [ParkingLotRatesClientModel.kRate]: this.rate,
      [ParkingLotRatesClientModel.kNightRate]: this.nightRate,
      [ParkingLotRatesClientModel.kMinimum]: this.minimum,
      [ParkingLotRatesClientModel.kMaximum]: this.maximum,
      [ParkingLotRatesClientModel.kDiscount]: this.discount,
      [ParkingLotRatesClientModel.kDynamicPricing]: this.dynamicPricing,
    };
  }

  toBodyFullParkingRate(): any {
    // Extend public representation with additional details suitable for public viewing
    return {
      ...this.toBodyPublicRate(),
      [ParkingLotRatesClientModel.kCreatedAt]: this.createdAt,
    };
  }
}
