import { ParkingReservation } from "../../../parkingReservation";

export class ParkingReservationClientModel extends ParkingReservation {
  static kReservationId = "reservationId";
  static kUserId = "userId";
  static kSlotId = "slotId";
  static kLotId = "lotId";
  static kVehicleId = "vehicleId";
  static kStartTime = "startTime";
  static kEndTime = "endTime";
  static kRateNumber = "rateNumber";
  static kRateType = "rateType";
  static kPrice = "price";
  static kTotalAmount = "totalAmount";
  static kStatus = "status";
  static kCreatedAt = "createdAt";

  static fromEntity(entity: ParkingReservation): ParkingReservationClientModel {
    return Object.assign(ParkingReservationClientModel.empty(), entity);
  }

  static empty(): ParkingReservationClientModel {
    return new ParkingReservationClientModel(
      "", // reservationId
      "", // userId
      "", // slotId
      "", // lotId
      "", // vehicleId
      null, // startTime
      null, // endTime
      0, // rateNumber
      null, // rateType
      0, // price
      0, // totalAmount
      null,
      new Date() // createdAt
    );
  }

  private static _validate(body: any) {}

  static validate(body: any, userId: string): ParkingReservationClientModel {
    this._validate(body);

    return new ParkingReservationClientModel(
      null, // reservationId is null as it will be generated by Firestore
      userId, // userId
      body[this.kSlotId],
      body[this.kLotId],
      body[this.kVehicleId],
      new Date(body[this.kStartTime]),
      new Date(body[this.kEndTime]),
      body[this.kRateNumber],
      body[this.kRateType],
      body[this.kPrice],
      body[this.kTotalAmount],
      body[this.kStatus],
      null // createdAt is null as it will be generated by Firestore
    );
  }

  toBodyPublicReservation(): any {
    return {
      [ParkingReservationClientModel.kReservationId]: this.reservationId,
      [ParkingReservationClientModel.kSlotId]: this.slotId,
      [ParkingReservationClientModel.kLotId]: this.lotId,
      [ParkingReservationClientModel.kVehicleId]: this.vehicleId,
      [ParkingReservationClientModel.kStartTime]: this.startTime.toISOString(),
      [ParkingReservationClientModel.kEndTime]: this.endTime.toISOString(),
      [ParkingReservationClientModel.kRateNumber]: this.rateNumber,
      [ParkingReservationClientModel.kRateType]: this.rateType,
      [ParkingReservationClientModel.kPrice]: this.price,
      [ParkingReservationClientModel.kTotalAmount]: this.totalAmount,
      [ParkingReservationClientModel.kStatus]: this.status,
    };
  }

  toBodyFullReservation(): any {
    return {
      ...this.toBodyPublicReservation(),
      [ParkingReservationClientModel.kUserId]: this.userId,
      [ParkingReservationClientModel.kCreatedAt]: this.createdAt.toISOString(),
    };
  }
}
