import { ParkingLot } from "../../../parkingLot";

export class ParkingLotClientModel extends ParkingLot {
  static kLotId = "LotId";
  static kLotName = "LotName";
  static kDescription = "Description";
  static kCoordinates = "Coordinates";
  static kAddress = "Address";
  static kCapacity = "Capacity";
  static kOccupancy = "Occupancy";
  static kLiveStatus = "LiveStatus";
  static kRate = "Rate";
  static kOperatingHours = "OperatingHours";
  static kFacilities = "Facilities";
  static kImages = "Images";
  static kStatus = "status";
  static kCreatedAt = "createdAt";

  static fromEntity(parkingLot: ParkingLot): ParkingLotClientModel {
    return Object.assign(ParkingLotClientModel.empty(), parkingLot);
  }

  static empty() {
    return new ParkingLotClientModel(
      "", // LotId
      "", // LotName
      "", // Description
      null, // Default Coordinates
      {
        streetNumber: "",
        unitNumber: "",
        streetName: "",
        city: "",
        state: "",
        country: "",
        postalCode: "",
        formattedAddress: "",
      }, // Empty Address
      0, // Capacity
      0, // Occupancy
      "Low", // LiveStatus
      [], // OperatingHours
      [], // Facilities
      [], // Images
      "Inactive", // Status
      new Date() // Current date
    );
  }

  private static _validate(body: any) {
    //Validation logic to be done here
  }

  static validate(body: any): ParkingLotClientModel {
    this._validate(body);
    // Assuming 'body' has all necessary fields to construct a ParkingLotClientModel
    return new ParkingLotClientModel(
      null, // LotId is null as it will be generated by Firestore
      body[ParkingLotClientModel.kLotName],
      body[ParkingLotClientModel.kDescription],
      body[ParkingLotClientModel.kCoordinates],
      body[ParkingLotClientModel.kAddress],
      body[ParkingLotClientModel.kCapacity],
      body[ParkingLotClientModel.kOccupancy],
      body[ParkingLotClientModel.kLiveStatus],
      body[ParkingLotClientModel.kOperatingHours],
      body[ParkingLotClientModel.kFacilities],
      body[ParkingLotClientModel.kImages],
      body[ParkingLotClientModel.kStatus],
      null // createdAt is null as it will be generated by Firestore
    );
  }

  /**
   * Converts the instance of ParkingLotClientModel to a full parking lot object.
   * This includes all properties of the parking lot, including those that are only available when the user is authenticated.
   * @returns {Object} An object that represents the full parking lot.
   */
  toBodyFullParkingLot() {
    return {
      ...this.toBodyPublicParkingLot(),
      [ParkingLotClientModel.kLotId]: this.LotId,
      [ParkingLotClientModel.kStatus]: this.status,
      [ParkingLotClientModel.kCreatedAt]: this.createdAt,
    };
  }
  /**
   * Converts the instance of ParkingLotClientModel to a public parking lot object.
   * This includes only the properties of the parking lot that are available to unauthenticated users.
   * @returns {Object} An object that represents the public parking lot.
   */
  toBodyPublicParkingLot() {
    return {
      [ParkingLotClientModel.kLotName]: this.LotName,
      [ParkingLotClientModel.kAddress]: this.Address,
      [ParkingLotClientModel.kCoordinates]: this.Coordinates,
      [ParkingLotClientModel.kDescription]: this.Description,
      [ParkingLotClientModel.kCapacity]: this.Capacity,
      [ParkingLotClientModel.kOccupancy]: this.Occupancy,
      [ParkingLotClientModel.kOperatingHours]: this.OperatingHours,
      [ParkingLotClientModel.kFacilities]: this.Facilities,
      [ParkingLotClientModel.kLiveStatus]: this.LiveStatus,
      [ParkingLotClientModel.kImages]: this.Images,
    };
  }
}
