import { GeoPoint } from "firebase-admin/firestore";
import { ParkingLot } from "../../../parkingLot";

export class ParkingLotClientModel extends ParkingLot {
  static kLotId = "LotId";
  static kCoordinates = "Coordinates";
  static kOwner = "Owner";
  static kCapacity = "Capacity";
  static kOccupancy = "Occupancy";
  static kLiveStatus = "LiveStatus";
  static kRate = "Rate";
  static kOperatingHours = "OperatingHours";
  static kFacilities = "Facilities";
  static kRates = "Rates";
  static kCreatedAt = "createdAt";

  static fromEntity(parkingLot: ParkingLot): ParkingLotClientModel {
    return Object.assign(ParkingLotClientModel.empty(), parkingLot);
  }

  static empty() {
    return new ParkingLotClientModel(
      "", // LotId
      new GeoPoint(0, 0), // Default Coordinates
      "", // Owner
      0, // Capacity
      0, // Occupancy
      "Low", // LiveStatus
      "", // Rate
      "", // OperatingHours
      [], // Facilities
      [], // Rates
      new Date() // Current date
    );
  }

  private static _validate(body: any) {
    // Here, validate the parking lot data
    console.log("Validating parking lot data to be done");
  }

  static validate(body: any, parkingOwnerId: string): ParkingLotClientModel {
    this._validate(body);
    // Assuming 'body' has all necessary fields to construct a ParkingLotClientModel
    return new ParkingLotClientModel(
      null, // LotId is null as it will be generated by Firestore
      body[ParkingLotClientModel.kCoordinates],
      parkingOwnerId,
      body[ParkingLotClientModel.kCapacity],
      body[ParkingLotClientModel.kOccupancy],
      body[ParkingLotClientModel.kLiveStatus],
      body[ParkingLotClientModel.kRate],
      body[ParkingLotClientModel.kOperatingHours],
      body[ParkingLotClientModel.kFacilities],
      body[ParkingLotClientModel.kRates],
      null // createdAt is null as it will be generated by Firestore
    );
  }

  /**
   * Converts the instance of ParkingLotClientModel to a full parking lot object.
   * This includes all properties of the parking lot, including those that are only available when the user is authenticated.
   * @returns {Object} An object that represents the full parking lot.
   */
  toBodyFullParkingLot() {
    return {
      ...this.toBodyPublicParkingLot(),
      [ParkingLotClientModel.kOccupancy]: this.Occupancy,
      [ParkingLotClientModel.kLiveStatus]: this.LiveStatus,
      [ParkingLotClientModel.kOperatingHours]: this.OperatingHours,
      [ParkingLotClientModel.kFacilities]: this.Facilities,
      [ParkingLotClientModel.kRates]: this.Rates,
    };
  }
  /**
   * Converts the instance of ParkingLotClientModel to a public parking lot object.
   * This includes only the properties of the parking lot that are available to unauthenticated users.
   * @returns {Object} An object that represents the public parking lot.
   */
  toBodyPublicParkingLot() {
    return {
      [ParkingLotClientModel.kLotId]: this.LotId,
      [ParkingLotClientModel.kCoordinates]: this.Coordinates,
      [ParkingLotClientModel.kOwner]: this.Owner,
      [ParkingLotClientModel.kCapacity]: this.Capacity,
      [ParkingLotClientModel.kRate]: this.Rate,
    };
  }
}
